# Generated by Django 4.0.4 on 2022-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_rename_occputation_employee_occputation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='occputation',
            field=models.CharField(max_length=30),
        ),
    ]
